---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: node-exporter
  name: node-exporter
spec:
  containers:
    - image: docker.io/prom/node-exporter:v1.5.0
      name: node-exporter
      args:
        - --path.rootfs=/host
      volumeMounts:
        - mountPath: /host
          name: root-host-0
          readOnly: true
      ports:
        - containerPort: 9100
          protocol: TCP
  volumes:
    - hostPath:
        path: /
        type: Directory
      name: root-host-0
