include:
  - project: "itops/gitlab-ci-templates"
    ref: "9.3.0"
    file: "terraform/terraform.gitlab-ci.yml"

terraform:validate:
  extends: .terraform:validate
  stage: test

terraform:test:
  extends: .terraform:test
  needs: ["terraform:validate"]
  variables:
    WORKDIR: tests
