include:
  - project: "itops/gitlab-ci-templates"
    ref: "10.2.2"
    file: "terraform/terraform.gitlab-ci.yml"

superduperlinter:
  stage: test
  variables:
    VALIDATE_KUBERNETES_KUBEVAL: "false"

terraform:validate:
  extends: .terraform:validate
  stage: test
