include:
  - project: "itops/gitlab-ci-templates"
    ref: "10.9.0"
    file: "terraform/terraform.gitlab-ci.yml"

superduperlinter:
  stage: test
  variables:
    # templated manifests
    VALIDATE_KUBERNETES_KUBECONFORM: "false"

terraform:validate:
  extends: .terraform:validate
  stage: test
