---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      # - id: terraform_tflint
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-system
        args: [./]
      - id: terraform-docs-system
        args: [./modules/pod]
      - id: terraform-docs-system
        args: [./modules/ca]
      - id: terraform-docs-system
        args: [./modules/directory_parents]
      - id: terraform-docs-system
        args: [./modules/node_exporter]
      - id: terraform-docs-system
        args: [./modules/open_vm_tools]
      - id: terraform-docs-system
        args: [./modules/authorized_keys]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # - id: no-commit-to-branch
      #   args: [--branch, master]
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: detect-private-key
      - id: end-of-file-fixer
